version: '3.8'

services:
  go-quick-gin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs