// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: service.go_quick_grpc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoQuickGRPC_SendHello_FullMethodName = "/pb.GoQuickGRPC/SendHello"
)

// GoQuickGRPCClient is the client API for GoQuickGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoQuickGRPCClient interface {
	SendHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type goQuickGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewGoQuickGRPCClient(cc grpc.ClientConnInterface) GoQuickGRPCClient {
	return &goQuickGRPCClient{cc}
}

func (c *goQuickGRPCClient) SendHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, GoQuickGRPC_SendHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoQuickGRPCServer is the server API for GoQuickGRPC service.
// All implementations must embed UnimplementedGoQuickGRPCServer
// for forward compatibility.
type GoQuickGRPCServer interface {
	SendHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedGoQuickGRPCServer()
}

// UnimplementedGoQuickGRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoQuickGRPCServer struct{}

func (UnimplementedGoQuickGRPCServer) SendHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHello not implemented")
}
func (UnimplementedGoQuickGRPCServer) mustEmbedUnimplementedGoQuickGRPCServer() {}
func (UnimplementedGoQuickGRPCServer) testEmbeddedByValue()                     {}

// UnsafeGoQuickGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoQuickGRPCServer will
// result in compilation errors.
type UnsafeGoQuickGRPCServer interface {
	mustEmbedUnimplementedGoQuickGRPCServer()
}

func RegisterGoQuickGRPCServer(s grpc.ServiceRegistrar, srv GoQuickGRPCServer) {
	// If the following call pancis, it indicates UnimplementedGoQuickGRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoQuickGRPC_ServiceDesc, srv)
}

func _GoQuickGRPC_SendHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoQuickGRPCServer).SendHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoQuickGRPC_SendHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoQuickGRPCServer).SendHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoQuickGRPC_ServiceDesc is the grpc.ServiceDesc for GoQuickGRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoQuickGRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GoQuickGRPC",
	HandlerType: (*GoQuickGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendHello",
			Handler:    _GoQuickGRPC_SendHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.go_quick_grpc.proto",
}
